/* 
This script creates the TREATMENT_TEST_PROCEDURE table.
*/
CREATE TABLE IF NOT EXISTS TREATMENT_TEST_PROCEDURE(
    -- 8 bit uuid
    Tid CHAR(8),
    `ICD-10-PCS_code` VARCHAR(7),
    `ICD-10-PCS_name` VARCHAR(255),
    Cost INT,
    Sid CHAR(8) NOT NULL,
    Vid CHAR(8) NOT NULL,
    PRIMARY KEY(`ICD-10-PCS_code`, Tid),
    FOREIGN KEY(Vid) REFERENCES VISIT_RECORD(Vid),
    FOREIGN KEY(Sid) REFERENCES SERVICE_PROVIDER(Sid)
);